# Python CircleCI 2.0 configuration file
python: &python
  docker:
    - image: circleci/python:3.6

version: 2

jobs:
  build:
    <<: *python
    steps:
      - checkout
      - run:
          name: Update PATH
          command: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install pipenv & bandit
          command: pip install --user pipenv bandit
      - run:
          name: Run tests
          command: pipenv install --dev && pipenv run make test
      - store_artifacts:
          path: test_results
      - store_test_results:
          path: test_results

  deploy:
    <<: *python
    steps:
      - checkout
      - run:
          name: Update PATH
          command: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Twine & Pipenv
          command: pip install --user twine pipenv
      - run:
          name: Push to cheeseshop
          command: ./push_to_cheeseshop.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^\d+(?:\.\d+){2}$/
            branches:
              ignore: /.*/
